version: '3.9'

services:
    server:
        build: .
        depends_on:
            - mongo
        ports:
            - "8080:8080"
        networks:
            - mongo
        environment:
            PORT: 8080
            MONGO_HOST: mongo
            MONGO_PORT: 27017
        env_file:
            - .env.production
        restart: always

    mongo:
        image: mongo:6
        ports:
            - "127.0.0.1:27017:27017"
        networks:
            - mongo
        env_file:
            - .env.production
        restart: always

networks:
    mongo: null
