version: '3.9'

services:
    server:
        build: .
        depends_on:
            - mongo-loader
        ports:
            - "8080:8080"
        networks:
            - mongo
        environment:
            PORT: 8080
            MONGO_HOST: mongo
            MONGO_PORT: 27017
        env_file:
            - .env.production
        restart: always

    mongo:
        image: mongo:6
        volumes:
            - mongo:/data/db
        ports:
            - "127.0.0.1:27017:27017"
        networks:
            - mongo
        env_file:
            - .env.production
        restart: always

    mongo-loader:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        depends_on:
            - mongo
        networks:
            - mongo
        environment:
            MONGO_HOST: mongo
            MONGO_PORT: 27017
        env_file:
            - .env.production
        restart: on-failure

networks:
    mongo: null

volumes:
    mongo: null
