FROM mongo:6

COPY users_dataset.json /app/users.json

CMD echo mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@$MONGO_HOST:$MONGO_PORT && mongoimport --uri "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@$MONGO_HOST:$MONGO_PORT/$MONGO_INITDB_DATABASE?authSource=admin" --db $MONGO_INITDB_DATABASE --collection users --type json --file /app/users.json --jsonArray