name: Beanstalk CD

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: npm ci

      - name: Create build
        run: npm run build

      - name: Generate deployment package
        run: zip -r deploy.zip * -x "**.git**"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Beanstalk Deploy my app
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY_ID}}
          application_name: ugram-backend
          environment_name: Ugrambackend-env-1
          region: us-east-2
          version_label: "${{ steps.date.outputs.date }}"
          deployment_package: deploy.zip
